### PR TITLE
feat:add mysql and sqlite support

### PR DESCRIPTION
**Pull request by czyt**

### CODE REVIEW

**Comment by unknwon** [comment]
Thanks for the PR! However, it is intentional to only support PostgreSQL. I may revisit this decision later so I'll keep this open for now.

**Comment by czyt** [comment]
> Thanks for the PR! However, it is intentional to only support PostgreSQL (a single DB backend with minimal maintenance burden). I may revisit this decision later so I'll keep this open for now.

ok,I prefer to use sqlite as database in small pjoject like you prefer postgres.😊

**Comment by unknwon** [comment]
I may actually consider using embedded PostgreSQL (to support running out-of-the-box) instead of introducing another DB backend to support it.

**Comment by unknwon** [comment]
I'm pretty certain that I'll proceed with the embedded PostgreSQL approach, thus closing this one and thanks again!

**Pull request closed without merging**
